project:
  metadata:
    key: fineract-chat-archive
    committee: fineract
    name: Slack Chat Archiver
notifications:
  commits: commits@fineract.apache.org
  pullrequests: issues@fineract.apache.org
github:
  description: 💾 Archive Slack messages into a static website.
  features:
    issues: true
  enabled_merge_buttons:
    merge: true
    squash: false
    rebase: false
  rulesets:
    - name: "Branch Protection"
      type: branch
      branches:
        includes:
          - "main"
      restrict_deletion: true
      restrict_force_push: true
      required_signatures: true
      required_linear_history: false
